import { useEffect, useState } from "react";
import { Ban, Blocks, Fingerprint, Link2, ShieldAlert, ShieldCheck, Clock as Unlock } from "lucide-react";
import { supabase, BlockchainNode, BlockchainTransaction, PoisonAlert } from "../lib/supabase";

const demoNodes: BlockchainNode[] = [
  { id: "n1", node_id: "NODE-001", device_name: "Factory Floor Gateway", device_type: "Industrial Gateway", reputation_score: 0.99, is_blocked: false, block_reason: null, updates_submitted: 28, updates_accepted: 28, updates_rejected: 0, last_update_hash: "7f2c...91ad", first_seen: "", last_seen: "" },
  { id: "n2", node_id: "NODE-002", device_name: "HVAC Controller Unit", device_type: "Environmental Sensor", reputation_score: 0.94, is_blocked: false, block_reason: null, updates_submitted: 28, updates_accepted: 27, updates_rejected: 1, last_update_hash: "3aa1...f03b", first_seen: "", last_seen: "" },
  { id: "n3", node_id: "NODE-003", device_name: "Security Camera — North Entrance", device_type: "IP Camera", reputation_score: 0.18, is_blocked: true, block_reason: "Model update anomaly: cosine distance 0.92", updates_submitted: 25, updates_accepted: 22, updates_rejected: 3, last_update_hash: "91e0...8c11", first_seen: "", last_seen: "" },
  { id: "n4", node_id: "NODE-004", device_name: "Smart Lock — Server Room", device_type: "Access Control", reputation_score: 0.98, is_blocked: false, block_reason: null, updates_submitted: 28, updates_accepted: 28, updates_rejected: 0, last_update_hash: "b772...6e2a", first_seen: "", last_seen: "" },
  { id: "n5", node_id: "NODE-005", device_name: "Temperature Sensor Array", device_type: "Environmental Sensor", reputation_score: 0.97, is_blocked: false, block_reason: null, updates_submitted: 27, updates_accepted: 27, updates_rejected: 0, last_update_hash: "5c4f...0d82", first_seen: "", last_seen: "" },
];
const demoTx: BlockchainTransaction[] = [
  { id: "t1", tx_hash: "0x8e42...a91f", block_number: 1842, node_id: "NODE-003", device_name: "Security Camera — North", round_number: 28, update_hash: "91e0...8c11", validation_score: 0.08, status: "rejected", rejection_reason: "Byzantine update: outside aggregate distance", timestamp: "2026-08-30T14:22:08Z" },
  { id: "t2", tx_hash: "0x7a19...c32d", block_number: 1841, node_id: "NODE-002", device_name: "HVAC Controller Unit", round_number: 28, update_hash: "3aa1...f03b", validation_score: 0.89, status: "accepted", rejection_reason: null, timestamp: "2026-08-30T14:20:48Z" },
  { id: "t3", tx_hash: "0x4f08...b720", block_number: 1840, node_id: "NODE-005", device_name: "Temperature Sensor Array", round_number: 28, update_hash: "5c4f...0d82", validation_score: 0.96, status: "accepted", rejection_reason: null, timestamp: "2026-08-30T14:20:31Z" },
  { id: "t4", tx_hash: "0x2b91...e31a", block_number: 1839, node_id: "NODE-001", device_name: "Factory Floor Gateway", round_number: 28, update_hash: "7f2c...91ad", validation_score: 0.98, status: "accepted", rejection_reason: null, timestamp: "2026-08-30T14:20:02Z" },
];
const demoAlerts: PoisonAlert[] = [{ id: "p1", node_id: "NODE-003", device_name: "Security Camera — North Entrance", round_number: 28, attack_type: "model_poisoning", severity: "critical", detection_method: "Cosine distance + reputation", anomaly_score: 0.92, action_taken: "blocked", description: "Update deviated sharply from the trusted global model. Node blocked before aggregation.", timestamp: "2026-08-30T14:22:08Z" }];

export default function Blockchain() {
  const [nodes, setNodes] = useState<BlockchainNode[]>(demoNodes);
  const [transactions, setTransactions] = useState<BlockchainTransaction[]>(demoTx);
  const [poisonAlerts, setPoisonAlerts] = useState<PoisonAlert[]>(demoAlerts);
  useEffect(() => { async function load(): Promise<void> { const [n, t, p] = await Promise.all([supabase.from("blockchain_nodes").select("*").order("reputation_score", { ascending: true }), supabase.from("blockchain_transactions").select("*").order("block_number", { ascending: false }), supabase.from("poison_alerts").select("*").order("timestamp", { ascending: false })]); if (!n.error && n.data?.length) setNodes(n.data as BlockchainNode[]); if (!t.error && t.data?.length) setTransactions(t.data as BlockchainTransaction[]); if (!p.error && p.data?.length) setPoisonAlerts(p.data as PoisonAlert[]); } void load(); }, []);

  const blocked = nodes.filter((node) => node.is_blocked).length;
  const accepted = transactions.filter((tx) => tx.status === "accepted").length;
  return <div className="page"><div className="page-header"><h1 className="page-title">Trust & Poison Blocking</h1><p className="page-subtitle">A validation gate prevents compromised clients from reaching the federated super-model.</p></div>
    <div className="trust-banner"><div className="trust-banner-icon"><Link2 size={22} /></div><div><strong>Pre-aggregation protection is active</strong><p>Every client update is hashed, scored, and recorded before it can influence the global model.</p></div><span className="pill pill-success"><span className="pill-dot" />Gate online</span></div>
    <div className="grid grid-cols-4" style={{ marginBottom: 20 }}><TrustMetric icon={<Blocks size={19} />} value="1,842" label="Latest block" tone="primary" /><TrustMetric icon={<ShieldCheck size={19} />} value={`${accepted}/${transactions.length}`} label="Recent updates accepted" tone="success" /><TrustMetric icon={<Ban size={19} />} value={blocked} label="Nodes blocked" tone="error" /><TrustMetric icon={<ShieldAlert size={19} />} value={poisonAlerts.length} label="Poison events stopped" tone="warning" /></div>
    <div className="grid grid-cols-2" style={{ marginBottom: 20 }}><div className="card"><div className="card-header"><div><div className="card-title">Node reputation & isolation</div><div className="card-subtitle">A blocked node cannot submit to the next aggregation round</div></div><span className="pipeline-model-badge">Quarantine gate</span></div><div className="node-list">{nodes.map((node) => <div className={`node-row ${node.is_blocked ? "blocked" : ""}`} key={node.id}><div className={`node-status-icon ${node.is_blocked ? "danger" : "safe"}`}>{node.is_blocked ? <Ban size={16} /> : <ShieldCheck size={16} />}</div><div className="node-info"><strong>{node.node_id}</strong><span>{node.device_name}</span></div><div className="node-reputation"><div className="reputation-top"><span>Reputation</span><strong>{(node.reputation_score * 100).toFixed(0)}%</strong></div><div className="reputation-track"><div className={`reputation-fill ${node.is_blocked ? "danger" : ""}`} style={{ width: `${node.reputation_score * 100}%` }} /></div></div><span className={`pill ${node.is_blocked ? "pill-error" : "pill-success"}`}><span className="pill-dot" />{node.is_blocked ? "Blocked" : "Trusted"}</span></div>)}</div></div>
      <div className="card"><div className="card-header"><div><div className="card-title">Poison attack response</div><div className="card-subtitle">Events stopped before global aggregation</div></div><span className="pill pill-error"><span className="pill-dot" />{poisonAlerts.length} critical</span></div>{poisonAlerts.map((alert) => <div className="poison-event" key={alert.id}><div className="poison-event-icon"><ShieldAlert size={18} /></div><div><div className="poison-event-top"><strong>{alert.attack_type.replace("_", " ")}</strong><span className="pill pill-error"><span className="pill-dot" />{alert.action_taken}</span></div><p>{alert.description}</p><small>{alert.node_id} · Round {alert.round_number} · Score {(alert.anomaly_score * 100).toFixed(0)}%</small></div></div>)}<div className="protection-flow"><FlowItem icon={<Fingerprint size={15} />} text="Hash update" /><span>→</span><FlowItem icon={<ShieldAlert size={15} />} text="Score anomaly" /><span>→</span><FlowItem icon={<Ban size={15} />} text="Block node" /><span>→</span><FlowItem icon={<Unlock size={15} />} text="Aggregate safe updates" /></div></div></div>
    <div className="card"><div className="card-header"><div><div className="card-title">Immutable update ledger</div><div className="card-subtitle">Transparent audit trail for each model contribution</div></div><div className="ledger-legend"><span><i className="legend-dot accepted" />Accepted</span><span><i className="legend-dot rejected" />Rejected</span></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Block</th><th>Transaction</th><th>Node</th><th>Round</th><th>Validation score</th><th>Status</th><th>Reason</th></tr></thead><tbody>{transactions.map((tx) => <tr key={tx.id}><td className="mono">#{tx.block_number}</td><td className="mono">{tx.tx_hash}</td><td><strong>{tx.node_id}</strong><div className="table-subtext">{tx.device_name}</div></td><td className="mono">R{tx.round_number}</td><td><div className="validation-cell"><div className="validation-track"><div className={`validation-fill ${tx.status}`} style={{ width: `${tx.validation_score * 100}%` }} /></div><span>{(tx.validation_score * 100).toFixed(0)}%</span></div></td><td><span className={`pill ${tx.status === "accepted" ? "pill-success" : tx.status === "rejected" ? "pill-error" : "pill-warning"}`}><span className="pill-dot" />{tx.status}</span></td><td className="table-subtext">{tx.rejection_reason ?? "Passed validation gate"}</td></tr>)}</tbody></table></div></div>
  </div>;
}
function TrustMetric({ icon, value, label, tone }: { icon: React.ReactNode; value: string | number; label: string; tone: "primary" | "success" | "warning" | "error" }) { return <div className="trust-metric"><div className={`trust-metric-icon ${tone}`}>{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>; }
function FlowItem({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flow-item">{icon}<span>{text}</span></div>; }
