import { useEffect, useState } from "react";
import { TriangleAlert as AlertTriangle, ArrowDownRight, ArrowUpRight, Brain, CircleCheck as CheckCircle2, Lightbulb, Search, ShieldQuestion } from "lucide-react";
import { supabase, XAIExplanation } from "../lib/supabase";

const demoExplanations: XAIExplanation[] = [
  { id: "x1", threat_id: "THRT-2026-0841", device_name: "Security Camera — North Entrance", attack_type: "Unauthorized Access Attempt", predicted_class: "Brute Force", confidence: 0.984, actual_class: "Brute Force", model_decision: "block", timestamp: "2026-08-30T14:22:08Z", top_features: [{ feature: "failed_logins", shap_value: 0.42, direction: "positive" }, { feature: "packet_rate", shap_value: 0.31, direction: "positive" }, { feature: "src_bytes", shap_value: 0.18, direction: "positive" }, { feature: "conn_state", shap_value: -0.12, direction: "negative" }, { feature: "service", shap_value: -0.06, direction: "negative" }] },
  { id: "x2", threat_id: "THRT-2026-0839", device_name: "HVAC Controller Unit", attack_type: "Anomalous Traffic Spike", predicted_class: "DDoS", confidence: 0.927, actual_class: "DDoS", model_decision: "investigate", timestamp: "2026-08-30T13:44:20Z", top_features: [{ feature: "dst_host_rate", shap_value: 0.38, direction: "positive" }, { feature: "byte_ratio", shap_value: 0.27, direction: "positive" }, { feature: "count", shap_value: 0.2, direction: "positive" }, { feature: "protocol_type", shap_value: -0.1, direction: "negative" }] },
  { id: "x3", threat_id: "THRT-2026-0838", device_name: "Smart Meter — Block C", attack_type: "Unencrypted Channel", predicted_class: "Policy Violation", confidence: 0.891, actual_class: "Policy Violation", model_decision: "remediate", timestamp: "2026-08-30T12:30:14Z", top_features: [{ feature: "service", shap_value: 0.35, direction: "positive" }, { feature: "protocol_type", shap_value: 0.29, direction: "positive" }, { feature: "flow_duration", shap_value: 0.11, direction: "positive" }, { feature: "jitter", shap_value: -0.08, direction: "negative" }] },
];

export default function XAI() {
  const [explanations, setExplanations] = useState<XAIExplanation[]>(demoExplanations);
  const [selected, setSelected] = useState<XAIExplanation>(demoExplanations[0]);
  const [query, setQuery] = useState("");

  useEffect(() => {
    async function load(): Promise<void> {
      const { data, error } = await supabase.from("xai_explanations").select("*").order("timestamp", { ascending: false });
      if (!error && data?.length) { const rows = data as XAIExplanation[]; setExplanations(rows); setSelected(rows[0]); }
    }
    void load();
  }, []);

  const filtered = explanations.filter((item) => `${item.device_name} ${item.attack_type} ${item.threat_id}`.toLowerCase().includes(query.toLowerCase()));
  const positiveFeatures = selected.top_features.filter((feature) => feature.direction === "positive");
  const maxValue = Math.max(...selected.top_features.map((feature) => Math.abs(feature.shap_value)), 0.01);

  return <div className="page"><div className="page-header"><h1 className="page-title">Explainable Detection</h1><p className="page-subtitle">SHAP-based evidence behind each BiLSTM decision, so operators can act with confidence.</p></div>
    <div className="xai-banner"><div className="xai-banner-icon"><Brain size={22} /></div><div><strong>Every alert has an evidence trail</strong><p>The model decision is shown with the features that pushed it toward or away from an attack classification.</p></div><span className="pill pill-success"><span className="pill-dot" />SHAP active</span></div>
    <div className="grid xai-layout"><div className="card"><div className="card-header"><div><div className="card-title">Detection explanations</div><div className="card-subtitle">Select an alert to inspect its model evidence</div></div><span className="xai-count">{filtered.length} explanations</span></div><div className="xai-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search device or threat..." /></div><div className="xai-alert-list">{filtered.map((item) => <button className={`xai-alert ${selected.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelected(item)}><div className={`xai-alert-icon ${item.model_decision}`}><AlertTriangle size={16} /></div><div className="xai-alert-body"><strong>{item.attack_type}</strong><span>{item.device_name}</span><small>{item.threat_id}</small></div><div className="xai-alert-confidence"><strong>{(item.confidence * 100).toFixed(1)}%</strong><span>confidence</span></div></button>)}</div></div>
      <div className="card"><div className="card-header"><div><div className="card-title">Why was this detected?</div><div className="card-subtitle">{selected.threat_id} · {selected.device_name}</div></div><span className={`pill ${selected.model_decision === "block" ? "pill-error" : "pill-warning"}`}><span className="pill-dot" />{selected.model_decision}</span></div><div className="xai-decision"><div className="xai-decision-score"><div className="xai-score-ring" style={{ "--score": `${selected.confidence * 100}%` } as React.CSSProperties}><strong>{(selected.confidence * 100).toFixed(0)}%</strong><span>confidence</span></div></div><div><div className="xai-decision-title">{selected.predicted_class}</div><p>The BiLSTM classified this sequence as <strong>{selected.predicted_class}</strong>. {selected.actual_class ? `Ground truth: ${selected.actual_class}.` : "Awaiting analyst confirmation."}</p></div></div><div className="xai-section-title"><Lightbulb size={15} /> Contributing features</div><div className="shap-list">{selected.top_features.map((feature) => <div className="shap-row" key={feature.feature}><div className={`shap-direction ${feature.direction}`} >{feature.direction === "positive" ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}</div><span className="shap-feature">{feature.feature}</span><div className="shap-track"><div className={`shap-fill ${feature.direction}`} style={{ width: `${(Math.abs(feature.shap_value) / maxValue) * 100}%` }} /></div><strong className={feature.direction}>{feature.shap_value > 0 ? "+" : ""}{feature.shap_value.toFixed(2)}</strong></div>)}</div><div className="xai-operator-note"><ShieldQuestion size={16} /><div><strong>Operator interpretation</strong><p>{positiveFeatures[0]?.feature ?? "The selected sequence"} was the strongest signal. Review the source device and apply the recommended {selected.model_decision} action.</p></div></div></div></div>
    <div className="grid grid-cols-3" style={{ marginTop: 20 }}><XAIStat icon={<CheckCircle2 size={18} />} value="96.8%" label="Explanations generated" tone="success" /><XAIStat icon={<Brain size={18} />} value="14" label="Selected model features" tone="primary" /><XAIStat icon={<ShieldQuestion size={18} />} value="< 80 ms" label="Explanation latency" tone="warning" /></div>
  </div>;
}
function XAIStat({ icon, value, label, tone }: { icon: React.ReactNode; value: string; label: string; tone: "success" | "primary" | "warning" }) { return <div className="xai-stat"><div className={`xai-stat-icon ${tone}`}>{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>; }
